version: "3.2"

services:
  vote:
    image: tobiasfenster/examplevotingapp_vote:dotnet-nanoserver-1809
    ports:
      - "5000:80"
    deploy:
      mode: replicated
      replicas: 4
    networks:
      - frontend
      - backend

  result:
    image: tobiasfenster/examplevotingapp_result:dotnet-nanoserver-1809
    environment:      
      - "ConnectionStrings:ResultData=Server=db;Database=votes;User Id=sa;Password=5uperSecret!"
    ports:
      - "5001:80"
    networks:
      - frontend
      - backend

  worker:
    image: tobiasfenster/examplevotingapp_worker:dotnet-nanoserver-1809
    environment:      
      - "ConnectionStrings:VoteData=Server=db;Database=votes;User Id=sa;Password=5uperSecret!"
    deploy:
      mode: replicated
      replicas: 3
    networks:
      - backend

  message-queue:
    image: nats:2.1-nanoserver-1809
    networks:
      - backend

  db:
    image: private-repo.microsoft.com/mssql-private-preview/mssql-server:windows-2019-rtm
    environment:
      - "ACCEPT_EULA=Y"
      - "MSSQL_SA_PASSWORD=5uperSecret!"
      - "MSSQL_PID=Developer"
    ports:
      - "1433:1433"

networks:
  frontend:
  backend: